### ISSUE TITLE
How to using the pre trained model to train my own dataset?

### ISSUE THREAD

**Issue by jackNhat** [mckinziebrandon/DeepChatModels#12]
First, thanks for great repository. I am newbie Chatbot, it helpful for me.
I have trained my own dataset and I have created my own model from scratch but it doesn't give good results.
I have added data then continue to train. But, I'm getting the following error:
```
ValueError: Cannot use 'decoder/while/decoder' as input to 'Merge/MergeSummary' because 'decoder/while/decoder' is in a while loop. See info log for more details.
````
How to solve the problem?

Thanks in advance!!!

**Comment by mckinziebrandon** [comment]
Hello, thanks for checking out the repo. Unfortunately, since this repo is written in TF version 1.2, it is too old for me to maintain anymore. I'd use it more as a reference for creating your own architectures, but the code itself is rather outdated (TF2.0 looks *much* different). 

With all that said, the error you are getting is saying that a `tf.summary` call was used somewhere on a tensor related-to or output-from a variable created by Decoder inside the body of a tf.while_loop. For a quick fix, you could remove any tf.summary calls related to the decoder code.

**Comment by jackNhat** [comment]
Thanks for reply @mckinziebrandon 
I downgraded the tf version to 1.2 and it worked.
Once again, thank you.
