### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by felansu** [mckinziebrandon/DeepChatModels#3]
For run in first instance need to install many dependencies.

It would be easier if exist requirements.txt.

Thanks!

**Comment by mckinziebrandon** [comment]
Thanks for posting. I just generated a requirements file (and removed some unused import dependencies in the data package). I'm going to test dependency issues more thoroughly in a virtual environment or docker, but this should be sufficient. 

Note that I'm hesitant to include a Tensorflow requirement for now because, for example, I compile from source and don't want versions getting mixed up. I'm currently running what should match the most recent pip release: `1.1.0-rc2`. With that said, the project should run just fine for any versions above 1.0. I'll be doing more testing to ensure that is the case. 

To generate the requirements file, I used the python package [https://github.com/bndr/pipreqs](https://github.com/bndr/pipreqs) via running `pipreqs ./` in the repository root directory. Let me know if you see anything that didn't get placed in the requirements file. I scanned the project to double-check but you can never be too sure.

**Comment by felansu** [comment]
Thanks you @mckinziebrandon !!
Now are running fine !
