### ISSUE TITLE
demo chatbot looks like a fool

### ISSUE THREAD

**Issue by tfzxyinhao** [mckinziebrandon/DeepChatModels#5]
![image](https://cloud.githubusercontent.com/assets/444814/26160228/416f7620-3b53-11e7-9f3f-d9ab5a1b0f77.png)

![image](https://cloud.githubusercontent.com/assets/444814/26160363/a53e50b8-3b53-11e7-88c4-f91091bf55d6.png)

![image](https://cloud.githubusercontent.com/assets/444814/26160424/d00e2624-3b53-11e7-8420-4cc371a6bc43.png)

**Comment by mckinziebrandon** [comment]
Yes, as briefly mentioned in the paragraph for that section, the web models are the absolute simplest models the project supports. More complex models take more time to train, are larger to store, and will have slightly longer response times. These are minor and unnoticeable differences if running locally, but they become rather important differences when trying to host on a website. Hence the initial decision to just upload the simplest models as a proof-of-concept really. 

I've got some models ready that use the BidirectionalEncoder with an AttentionDecoder, and perhaps I'll deploy one on the site soon for a comparison. It might be a bit slower though!

Since I've taken your feedback into account and agree the demo bot is indeed a fool, I'll close this issue tomorrow unless there's anything else you'd like to bring up. Thanks!
